/**
 * Shared surface textures. The grid takes its colour from `currentColor`, so a
 * parent sets the tone with a text utility and the pattern follows the palette.
 */

/**
 * Technical grid. `id` must be unique per instance — SVG pattern ids are
 * document-global, so two grids sharing one id would render the same fill.
 */
export function GridPattern({
  id,
  size = 56,
  opacity = 0.6,
  className = "",
}: {
  id: string;
  size?: number;
  opacity?: number;
  className?: string;
}) {
  return (
    <svg
      aria-hidden="true"
      className={`pointer-events-none absolute inset-0 h-full w-full ${className}`}
      fill="none"
    >
      <defs>
        <pattern id={id} width={size} height={size} patternUnits="userSpaceOnUse">
          <path
            d={`M${size} 0H0V${size}`}
            stroke="currentColor"
            strokeWidth="1"
            fill="none"
          />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill={`url(#${id})`} opacity={opacity} />
    </svg>
  );
}

const GRAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")";

/**
 * Film grain. Generated by an inline SVG filter rather than a bitmap, so it
 * costs no request and tiles at any size. Keeps large flat fills from reading
 * as printed-flat screen colour.
 */
export function Grain({ opacity = 0.14 }: { opacity?: number }) {
  return (
    <span
      aria-hidden="true"
      className="pointer-events-none absolute inset-0 mix-blend-multiply"
      style={{ backgroundImage: GRAIN, opacity }}
    />
  );
}

