import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_eyebrow\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_primary_label\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_primary_href\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_secondary_label\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_secondary_href\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_status_text\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_status_metric_label\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`hero_status_metric_value\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`services_lead_badge\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`services_membership_badge\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`services_membership_title\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`services_membership_cta_label\`;`)
  await db.run(sql`ALTER TABLE \`home\` DROP COLUMN \`services_membership_cta_href\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_eyebrow\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_primary_label\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_primary_href\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_secondary_label\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_secondary_href\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_status_text\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_status_metric_label\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_hero_status_metric_value\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_services_lead_badge\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_services_membership_badge\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_services_membership_title\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_services_membership_cta_label\`;`)
  await db.run(sql`ALTER TABLE \`_home_v\` DROP COLUMN \`version_services_membership_cta_href\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_eyebrow\` text DEFAULT 'Est. 2026 — Bespoke Care';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_primary_label\` text DEFAULT 'Request a Quote →';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_primary_href\` text DEFAULT '#book';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_secondary_label\` text DEFAULT 'View recent work';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_secondary_href\` text DEFAULT '/gallery';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_status_text\` text DEFAULT 'Live Status: Professionals active nearby';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_status_metric_label\` text DEFAULT 'Avg. response';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`hero_status_metric_value\` text DEFAULT '~12 min';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`services_lead_badge\` text DEFAULT 'Signature';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`services_membership_badge\` text DEFAULT 'Membership';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`services_membership_title\` text DEFAULT 'Recurring care, on your schedule.';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`services_membership_cta_label\` text DEFAULT 'See plans';`)
  await db.run(sql`ALTER TABLE \`home\` ADD \`services_membership_cta_href\` text DEFAULT '/#book';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_eyebrow\` text DEFAULT 'Est. 2026 — Bespoke Care';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_primary_label\` text DEFAULT 'Request a Quote →';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_primary_href\` text DEFAULT '#book';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_secondary_label\` text DEFAULT 'View recent work';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_secondary_href\` text DEFAULT '/gallery';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_status_text\` text DEFAULT 'Live Status: Professionals active nearby';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_status_metric_label\` text DEFAULT 'Avg. response';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_hero_status_metric_value\` text DEFAULT '~12 min';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_services_lead_badge\` text DEFAULT 'Signature';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_services_membership_badge\` text DEFAULT 'Membership';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_services_membership_title\` text DEFAULT 'Recurring care, on your schedule.';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_services_membership_cta_label\` text DEFAULT 'See plans';`)
  await db.run(sql`ALTER TABLE \`_home_v\` ADD \`version_services_membership_cta_href\` text DEFAULT '/#book';`)
}
